# Generated by Django 4.0.2 on 2022-02-20 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=15)),
                ('country', models.CharField(blank=True, default='', max_length=30)),
                ('countryCode', models.CharField(default='', max_length=2)),
                ('region', models.CharField(default='', max_length=2)),
                ('regionName', models.CharField(default='', max_length=30)),
                ('city', models.CharField(default='', max_length=30)),
                ('zip', models.CharField(default='', max_length=10)),
                ('lat', models.CharField(default='', max_length=10)),
                ('lon', models.CharField(default='', max_length=10)),
                ('timezone', models.CharField(default='', max_length=25)),
                ('isp', models.CharField(default='', max_length=50)),
                ('org', models.CharField(default='', max_length=50)),
                ('asn', models.CharField(default='', max_length=50)),
                ('query', models.CharField(default='', max_length=15)),
                ('consulted', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['consulted'],
            },
        ),
    ]
